# Generated by Django 5.2.8 on 2026-08-06 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projets', '0002_difficulte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tache',
            name='priorite',
            field=models.CharField(choices=[('critique', 'Critique'), ('haute', 'Haute'), ('normale', 'Normale')], default='normale', max_length=10),
        ),
    ]
