# Generated by Django 5.2.8 on 2026-08-23 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projets', '0003_alter_tache_priorite'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermissionMembreProjet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('taches.gerer', 'Gérer les tâches'), ('activites.gerer', 'Gérer les activités'), ('equipe.gerer', "Gérer l'équipe"), ('projet.gerer', 'Modifier/supprimer le projet')], max_length=30)),
                ('accordee', models.BooleanField(default=True)),
                ('mis_a_jour_le', models.DateTimeField(auto_now=True)),
                ('membre_projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions_directes', to='projets.membreprojet')),
            ],
            options={
                'unique_together': {('membre_projet', 'code')},
            },
        ),
    ]
