services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: agt_backend
    volumes:
      - db_data:/data
    environment:
      DB_PATH: /data/taskflow.db
      FLASK_ENV: production
      FLASK_DEBUG: "0"
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: agt_frontend
    ports:
      - "80:80"
      - "443:443"
    volumes:
      # Partage des certificats SSL du VPS vers le conteneur Nginx
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  db_data:
