# Generated by Django 5.2.8 on 2026-08-05 16:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('slug', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='PertStatut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cle', models.SlugField(max_length=30, unique=True)),
                ('label', models.CharField(max_length=60)),
                ('couleur', models.CharField(default='#6b7280', max_length=20)),
                ('ordre', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['ordre', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Edge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_num', models.IntegerField()),
                ('to_num', models.IntegerField()),
                ('label', models.CharField(blank=True, default='', max_length=80)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edges', to='pilotage_stage.branch')),
            ],
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField()),
                ('kind', models.CharField(choices=[('start', 'start'), ('work', 'work'), ('valid', 'valid'), ('auto', 'auto'), ('final', 'final')], max_length=10)),
                ('titre', models.CharField(max_length=120)),
                ('x', models.IntegerField(default=0)),
                ('y', models.IntegerField(default=0)),
                ('blocking', models.BooleanField(default=False)),
                ('detail', models.TextField(blank=True, default='')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='pilotage_stage.branch')),
            ],
            options={
                'ordering': ['branch', 'num'],
                'unique_together': {('branch', 'num')},
            },
        ),
        migrations.CreateModel(
            name='PertTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=250)),
                ('preds', models.JSONField(blank=True, default=list)),
                ('dur', models.IntegerField(default=1)),
                ('statut', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='taches_pert', to='pilotage_stage.pertstatut')),
            ],
            options={
                'ordering': ['num'],
            },
        ),
        migrations.CreateModel(
            name='Tache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True, default='')),
                ('jour', models.CharField(blank=True, default='', max_length=40)),
                ('bloc', models.CharField(blank=True, choices=[('prep', 'prep'), ('critique', 'critique'), ('rituel', 'rituel')], default='', max_length=12)),
                ('benef', models.CharField(blank=True, default='', max_length=60)),
                ('note', models.TextField(blank=True, default='')),
                ('ordre', models.IntegerField(default=0)),
                ('clos', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assignee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='taches_pilotage_assignees', to=settings.AUTH_USER_MODEL)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='taches', to='pilotage_stage.branch')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='taches_pilotage_creees', to=settings.AUTH_USER_MODEL)),
                ('current_node', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='pilotage_stage.node')),
                ('pert_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taches', to='pilotage_stage.perttask')),
                ('validateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='taches_pilotage_a_valider', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['jour', 'ordre', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SousTache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=250)),
                ('statut', models.CharField(choices=[('a_faire', 'a_faire'), ('en_cours', 'en_cours'), ('bloque', 'bloque'), ('fait', 'fait')], default='a_faire', max_length=15)),
                ('ordre', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tache', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sous_taches', to='pilotage_stage.tache')),
            ],
            options={
                'ordering': ['ordre', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Sollicitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('de', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('vers', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tache', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sollicitations', to='pilotage_stage.tache')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Transition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentaire', models.CharField(blank=True, default='', max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_node', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='pilotage_stage.node')),
                ('par', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tache', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transitions', to='pilotage_stage.tache')),
                ('to_node', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='pilotage_stage.node')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
