# Generated by Django 5.2.8 on 2026-08-06 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0002_seed_rbac'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='color',
            field=models.CharField(default='#6366f1', max_length=7),
        ),
    ]
