# Generated by Django 5.2.8 on 2026-08-06 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0003_user_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='doit_changer_mdp',
            field=models.BooleanField(default=False),
        ),
    ]
