# Generated by Django 5.2.8 on 2026-08-17 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0002_seed_finances_permissions'),
        ('rh', '0004_seed_conges_notes_frais_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='FichePaie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periode', models.DateField()),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('statut', models.CharField(choices=[('generee', 'Générée'), ('consultee', 'Consultée')], default='generee', max_length=20)),
                ('date_generation', models.DateTimeField(auto_now_add=True)),
                ('contrat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fiches_paie', to='rh.contrat')),
                ('mouvement_financier', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fiche_paie', to='finances.mouvementfinancier')),
                ('remuneration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fiches_paie', to='rh.remuneration')),
            ],
            options={
                'ordering': ['-periode'],
                'constraints': [models.UniqueConstraint(fields=('contrat', 'periode'), name='fiche_paie_unique_par_mois')],
            },
        ),
    ]
