# Generated by Django 5.2.8 on 2026-08-09 06:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projets', '0003_alter_tache_priorite'),
        ('rh', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeMouvementFinancier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('sens', models.CharField(choices=[('entree', 'Entrée'), ('sortie', 'Sortie')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Prevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periode_debut', models.DateField()),
                ('periode_fin', models.DateField()),
                ('montant_prevu', models.DecimalField(decimal_places=2, max_digits=12)),
                ('niveau', models.CharField(choices=[('entreprise', 'Entreprise'), ('projet', 'Projet'), ('employe', 'Employé')], max_length=20)),
                ('employe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previsions', to='rh.employe')),
                ('projet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previsions', to='projets.projet')),
            ],
            options={
                'ordering': ['-periode_debut'],
            },
        ),
        migrations.CreateModel(
            name='RapportFinancier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('format', models.CharField(choices=[('pdf', 'PDF'), ('txt', 'TXT')], max_length=5)),
                ('periode_debut', models.DateField()),
                ('periode_fin', models.DateField()),
                ('genere_le', models.DateTimeField(auto_now_add=True)),
                ('genere_par', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rapports_financiers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-genere_le'],
            },
        ),
        migrations.CreateModel(
            name='MouvementFinancier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date_mouvement', models.DateTimeField(auto_now_add=True)),
                ('niveau', models.CharField(choices=[('entreprise', 'Entreprise'), ('projet', 'Projet'), ('employe', 'Employé')], max_length=20)),
                ('employe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mouvements_financiers', to='rh.employe')),
                ('projet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mouvements_financiers', to='projets.projet')),
                ('remuneration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mouvements_generes', to='rh.remuneration')),
                ('type_mouvement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mouvements', to='finances.typemouvementfinancier')),
            ],
            options={
                'ordering': ['-date_mouvement'],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('employe__isnull', True), ('niveau', 'entreprise'), ('projet__isnull', True)), models.Q(('employe__isnull', True), ('niveau', 'projet'), ('projet__isnull', False)), models.Q(('employe__isnull', False), ('niveau', 'employe')), _connector='OR'), name='mouvement_niveau_coherent')],
            },
        ),
    ]
