# Generated by Django 5.2.8 on 2026-08-23 19:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def renommer_rebut_en_hors_service(apps, schema_editor):
    """BF-05 : "rebut" est remplacé par "hors service" — les mouvements
    existants doivent suivre, pas seulement le catalogue de choix."""
    MouvementMateriel = apps.get_model("materiel", "MouvementMateriel")
    MouvementMateriel.objects.filter(type_mouvement="rebut").update(type_mouvement="hors_service")


def annuler(apps, schema_editor):
    MouvementMateriel = apps.get_model("materiel", "MouvementMateriel")
    MouvementMateriel.objects.filter(type_mouvement="hors_service").update(type_mouvement="rebut")


class Migration(migrations.Migration):

    dependencies = [
        ('materiel', '0003_seed_membre_materiel_read'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='mouvementmateriel',
            name='type_mouvement',
            field=models.CharField(choices=[('achat', 'Achat'), ('affectation', 'Affectation'), ('retour', 'Retour'), ('hors_service', 'Hors service'), ('consommation', 'Consommation')], max_length=15),
        ),
        migrations.CreateModel(
            name='AlerteMateriel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_alerte', models.CharField(choices=[('rupture_stock', 'Rupture de stock'), ('anomalie', 'Anomalie'), ('rappel', 'Rappel')], max_length=20)),
                ('message', models.CharField(blank=True, default='', max_length=250)),
                ('statut', models.CharField(choices=[('ouverte', 'Ouverte'), ('traitee', 'Traitée')], default='ouverte', max_length=10)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('traitee_le', models.DateTimeField(blank=True, null=True)),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('materiel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertes', to='materiel.materiel')),
                ('traitee_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-cree_le'],
            },
        ),
        migrations.RunPython(renommer_rebut_en_hors_service, annuler),
    ]
